# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: arsiddiq <arsiddiq@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/23 17:15:06 by arsiddiq          #+#    #+#              #
#    Updated: 2019/07/23 18:25:39 by arsiddiq         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLAGS= -Wall -Werror -Wextra
SRCS = main.c utilities.c
NAME = do-op

all:
	gcc -o $(NAME) $(SRCS) $< $(CFLAGS)

clean:
	rm -f $(NAME)
